### ISSUE TITLE
Checklist du rendu final

### ISSUE THREAD

**Issue by Colnup** [ThimoteB/Potich-Adventures#25]
## HESITEZ PAS A EN RAJOUTER

Liste des choses à faire pour le rendu final:

- [ ] Relire les issues pas fermées / documenter pourquoi ça n'a pas été fait.
- [ ] jeu en fullscreen
- [ ] playtest en réseau et solo
- [ ] release github
- [ ] revoir la valeur de regression pour chaque goal
